### ISSUE TITLE
failureRedirect option not working in version 0.2.0

### ISSUE THREAD

**Issue by xoen** [auth0/passport-auth0-openidconnect#5]
Hello,

We've upgraded to `passport-auth0-openidconnect` to `0.2.0`. After this upgrade the `failureRedirect` option doesn't seem to work anymore. Instead of redirecting it's raising an `AuthorizationError`:

```
AuthorizationError: Multifactor authentication required
    at Strategy.authenticate (/Users/xoen/Projects/analytics-platform-rstudio-auth-proxy/node_modules/passport-openidconnect/lib/strategy.js:74:25)
    at attempt (/Users/xoen/Projects/analytics-platform-rstudio-auth-proxy/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/Users/xoen/Projects/analytics-platform-rstudio-auth-proxy/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/Users/xoen/Projects/analytics-platform-rstudio-auth-proxy/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/xoen/Projects/analytics-platform-rstudio-auth-proxy/node_modules/express/lib/router/route.js:137:13)
    at router.get (/Users/xoen/Projects/analytics-platform-rstudio-auth-proxy/app/routes.js:46:5)
    at Layer.handle [as handle_request] (/Users/xoen/Projects/analytics-platform-rstudio-auth-proxy/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/xoen/Projects/analytics-platform-rstudio-auth-proxy/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/xoen/Projects/analytics-platform-rstudio-auth-proxy/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/xoen/Projects/analytics-platform-rstudio-auth-proxy/node_modules/express/lib/router/layer.js:95:5)
```

I'm not quite sure why, nothing else in the application changed.

**Comment by xoen** [comment]
Interestingly, same upgrade in a very similar application seems to work fine.

**Comment by xoen** [comment]
Just to be clear, when I say "[...] the failureRedirect option doesn't seem to work anymore." it's my guess as I would expect that option to redirect the user back to the login page (the app is calling `passport.authenticate('auth0-oidc', { failureRedirect: '/login?prompt=true' })`)...I'm not really sure what is the problem or where it is exactly.

I suspect it may be somehow caused by the change to [use of `passport-openidconnect-0.0.2`](https://github.com/auth0/passport-auth0-openidconnect/commit/26a58aa52a88bbb707ec6616c2dafb93ff25475f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)  instead of the siacomuzzi's fork.
